#!/bin/sh
#
# This script recreates hpdf_page_sizes.h file
# In order to use it install Jinja2 using
# `pip3 install jinja2-cli`
#
# File is generated by executing hpdf_page_sizes.template.
#

J=~/.local/bin/jinja2
RES=../include/hpdf_page_sizes.h

cat hpdf_page_sizes.json | $J hpdf_page_sizes.template > $RES